### ISSUE TITLE
Expected class name PipelineModel but found class name CrossValidatorModel

### ISSUE THREAD

**Issue by paul-reiners** [PacktPublishing/Scala-Machine-Learning-Projects#1]
Hi,

I'm getting the following error:

```
Caused by: java.lang.IllegalArgumentException: requirement failed: Error loading metadata: Expected class name org.apache.spark.ml.PipelineModel but found class name org.apache.spark.ml.tuning.CrossValidatorModel
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.util.DefaultParamsReader$.parseMetadata(ReadWrite.scala:404)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:383)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:266)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:347)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:341)
	at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:218)
	at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:331)
	at prediction.PredictionActor$$anonfun$1.apply(PredictionActor.scala:38)
	at prediction.PredictionActor$$anonfun$1.apply(PredictionActor.scala:38)
        .
        .
        .
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	... 9 more

```
When I change the type to `CrossValidatorModel`, I get an error saying it is expecting `PipelineModel`.

How can I fix this?

**Comment by rezacsedu** [comment]
Hi,

Where did you get this error? I mean in which chapter? Could you please explain? Anyway, seeing the issue, I suspect that you're confused between PipelineModel and CrossValidatorModel. 

Nevertheless, if this is about chapter 3, then I guess your trained model is a cross-validated model but in the application, you're referring the pipeline model. 

**How to fix the issue?**
Well, there are two options actually: 
1. Using my own implementation blindly
2. Replacing the actual model with you'rs one (CrossValidated or Pipeline whatever you've)

**Option 1:** First, download the `Bitcoin_price_prediction.tar.gz` file from this repo, unzip it and go to the following directory: 
`$ cd Bitcoin_price_prediction.tar\Bitcoin_price_prediction\bitcoin_ml\conf`
Then change the following lines with actual path:
rootDir = "/home/asif/Downloads/Bitcoin_price_prediction/"
db.default.url = "jdbc:h2://home/asif/Downloads/Bitcoin_price_prediction/DataBase"
Then execute the folllowing: 
`$ cd .. `
`$ sudo sbt run`

Now you should experience the following output on the browser at http://localhost:9000/. 

![grafik](https://user-images.githubusercontent.com/14220009/39094473-3db076cc-4630-11e8-9172-d9e982d5c14d.png)

**Option 2:** First, download the `Bitcoin_price_prediction.tar.gz` file from this repo, unzip it and go to the following directory: 

`$ cd Bitcoin_price_prediction.tar\Bitcoin_price_prediction\bitcoin_ml\conf`
Then change the following lines with the actual path to your trained CrossValidated or Pipeline model. Also make sure you change the rootDir  and db.default.url as shown above:
ml.model_version = "gbt_22_binary_classes_32660767.model"

Then do the following: 
`$ cd .. `
`$ sudo sbt run`

Hope that helps. If you need any further, please let me know.

**Comment by paul-reiners** [comment]
I found the problem.  Thanks, anyway.

**Comment by rezacsedu** [comment]
@paul-reiners, so what was the issue exactly?

**Comment by paul-reiners** [comment]
I was trying to load the wrong file.  The error message was exactly correct.  I was just being impatient that day.  Sorry about that.

**Comment by rezacsedu** [comment]
@paul-reiners, glad knowing that the issue has been resolved. However, please don't hesitate to file issues if you experience any bug and I will try to fix them ASAP. 

Thanks.
